// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkk4pi_W_X_SVSFKBicVgl3vvZIh3LRkc',
    appId: '1:555426828806:web:1f0ba4c49ce16b2a4f6987',
    messagingSenderId: '555426828806',
    projectId: 'bonsight-3887f',
    authDomain: 'bonsight-3887f.firebaseapp.com',
    storageBucket: 'bonsight-3887f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-6QJIoAysjMN0bbhYLRYMQrV-MybahR4',
    appId: '1:555426828806:android:5124dbac567303104f6987',
    messagingSenderId: '555426828806',
    projectId: 'bonsight-3887f',
    storageBucket: 'bonsight-3887f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEvRkV1txt11MLHOH_RU_Iqck7Jkk4rMU',
    appId: '1:555426828806:ios:11d97932b28736154f6987',
    messagingSenderId: '555426828806',
    projectId: 'bonsight-3887f',
    storageBucket: 'bonsight-3887f.firebasestorage.app',
    iosBundleId: 'com.example.bonssight',
  );
}
